name = "url-shortener"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Enable importing non-JS modules (HTML, CSS, JS from public) as text
rules = [
  { type = "Text", globs = ["public/*.html", "public/*.css", "public/*.js"], fallthrough = true }
]

# KV Namespace binding for URL storage
[[kv_namespaces]]
binding = "URLS"
id = "04d05ce9af164da4aee29991fdf56f50"
preview_id = "04d05ce9af164da4aee29991fdf56f50"
